GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "How to Write a Killer Blog Post",
    "author": "Maliha",
    "url": "https://www.thesideblogger.com/how-to-write-a-blog-post/",
    "likes": 35,
    "userId": "6744b3bae758473c00c05d2d"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "The 18 Best Bars in Boston",
    "author": "Todd Plummer",
    "url": "https://www.cntraveler.com/gallery/best-bars-in-boston",
    "likes": 647,
    "userId": "6744b3cee758473c00c05d2f"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "The 13 best chocolates",
    "author": "Anne Wolf",
    "url": "https://www.businessinsider.com/guides/kitchen/best-chocolate",
    "userId": "6744b3cee758473c00c05d2f"
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN5ZG5leWRlbGwiLCJpZCI6IjY3NDRiM2JhZTc1ODQ3M2MwMGMwNWQyZCIsImlhdCI6MTczMjU2MzExNH0.BQdMgnK4zlZc3nL_DU6KzWMMLKpp7I9R6EIDBhPuVaI

{
    "title": "A New Blog Post",
    "author": "A new person",
    "url": "https://www.businessinsider.com/guides/kitchen/best-chocolate",
    "userId": "6744cfee2d27df29304de76d"
}
