GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "sydneydell",
    "name": "Sydney D",
    "password": "tuesday12"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "dellsydney",
    "name": "Australia",
    "password": "friday129"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "authorized2",
    "name": "Authorized2",
    "password": "monday23902"
}