POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "703439435"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Dell"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "704-774-7489"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Art",
    "number": "704348597489"
}